会場を株式会社インプレスに更新した
ko-kisaitou/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:31 UTC by ko-kisaitou

hhhhhhhhhhhh

2024-06-06 05:33 UTC, Im1337xd reviewed
いいいいいいいいいいい

2024-06-06 05:37 UTC, ko-kisaitou commented
@Im1337xd test

2024-06-06 05:38 UTC, ko-kisaitou commented
> いいいいいいいいいいい

uuuuuuuuuuuuuuuuu

2024-06-06 05:38 UTC, matsui0412 reviewed
いいね。あうあう

2024-06-06 05:41 UTC, ko-kisaitou commented
> いいね。あうあう

お前はだれだ？！俺の中の俺

2024-06-06 05:41 UTC, yasuda-s23016 commented
mieruzo

2024-06-06 05:42 UTC, ko-kisaitou commented
> mieruzo

うんこ

2024-06-06 05:43 UTC, ko-kisaitou commented
@matsui0412 アベイラビリティゾーン意識しろ

2024-06-06 05:46 UTC, ko-kisaitou commented
@Im1337xd 嗨，來自遠方的你，今天會收到一個驚喜

2024-06-06 05:47 UTC, ko-kisaitou commented
@yasuda-s23016 嗨，來自遠方的你，今天會收到一個驚喜

2024-06-12 02:36 UTC, matsui0412 requested changes
修正謝謝茄子

2024-06-12 02:36 UTC, matsui0412 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社松井に変えてください

2024-06-12 03:32 UTC, matsui0412 approved these changes

2024-06-13 04:57 UTC, merged